# Generated by Django 2.2.2 on 2019-06-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=100)),
                ('cmyk', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_base', models.IntegerField()),
                ('stock_black', models.IntegerField()),
                ('stock_yellow', models.IntegerField()),
                ('stock_magenta', models.IntegerField()),
                ('stock_cyan', models.IntegerField()),
                ('stock_status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StockObserver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demanded_colors', models.ManyToManyField(to='color_in.Color')),
            ],
        ),
    ]
